### ISSUE TITLE
0.7.0 GUI traceback with multi-image captchas when quickly clicking verify

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/librecaptcha#11]
0.7.0 gives a traceback for the GUI with multi-image captchas when I quickly click the bottom right most image and then (before the latency mentioned in #10 expires) click verify multiple times, eventually I will get a traceback, sometimes early, sometimes when I get transitioned to the tiled captchas. The librecaptcha GUI disappears at this point. This is with the old SlimIt based code.

```
$ ./librecaptcha.py -g $key $site
An unexpected error occurred. The exception traceback is shown below:

Traceback (most recent call last):
  File "./librecaptcha.py", line 22, in <module>
    main()
  File "librecaptcha/__main__.py", line 276, in main
    run_or_exit(parsed)
  File "librecaptcha/__main__.py", line 243, in run_or_exit
    return run(args)
  File "librecaptcha/__main__.py", line 215, in run
    uvtoken = get_token(
  File "librecaptcha/librecaptcha.py", line 78, in get_token
    return ui.run()
  File "librecaptcha/gui.py", line 419, in run
    self.dispatch(FinishChallenge())
  File "librecaptcha/gui.py", line 484, in dispatch
    self.dispatch_multicaptcha(msg)
  File "librecaptcha/gui.py", line 507, in dispatch_multicaptcha
    self.multicaptcha_finish()
  File "librecaptcha/gui.py", line 512, in multicaptcha_finish
    result = self.solver.select_indices(self.store.state.indices)
AttributeError: 'NoneType' object has no attribute 'indices'
```

**Comment by taylordotfish** [comment]
I think 0.7.1 fixes this. I couldn't actually reproduce it (probably because request latency is lower for me, which is also why I didn't notice #10), but I think I understand how it could happen.
