### ISSUE TITLE
tracebacks with GUI version

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/librecaptcha#5]
I got a traceback when trying the new GUI option. With the dynamic challenges, when I click verify before the images I have clicked are reloaded, then I get a traceback for each missing image.

With the dynamic challenges, the verify button needs to be disabled or hidden after clicking on an image until all of the clicked images are replaced with new ones. The space to the left could have some text to explain the disablement.

```
$ curl -s https://gitlab.gnome.org/users/sign_in | grep data-sitekey
<div class="g-recaptcha" data-sitekey="6Lfhei8UAAAAAKwEVuEwxJX09r0AGdMm-DUTWNAQ"></div>

$ ./librecaptcha.py --gui 6Lfhei8UAAAAAKwEVuEwxJX09r0AGdMm-DUTWNAQ https://gitlab.gnome.org/
Submitting solution...
Submitting solution...
Submitting solution...
Submitting solution...
Submitting solution...
You must solve another challenge.

Submitting solution...
Submitting solution...
Submitting solution...
Submitting solution...
Submitting solution...
You must solve another challenge.

Submitting solution...
You must solve another challenge.

Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Submitting solution...
You must solve another challenge.

Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Submitting solution...
You must solve another challenge.

Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Submitting solution...
You must solve another challenge.

Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "librecaptcha/gui.py", line 374, in callback
    self.dialog.replace_tile_image(index, image)
  File "librecaptcha/gui.py", line 295, in replace_tile_image
    self.dialog.replace_grid_item(index, button)
  File "librecaptcha/gui.py", line 169, in replace_grid_item
    self.grid.remove(old)
TypeError: Argument 1 does not allow None as a value
```

**Comment by taylordotfish** [comment]
Fixed in version 0.7.0. Among other changes to the GUI, the “Verify” button is disabled while there are images loading.

Note that this version also uses [this Python port of esprima](https://pypi.org/project/esprima/) for JavaScript parsing rather than slimit. However, for now, if esprima isn’t installed, the old slimit-based implementation is used as a fallback.
